@startuml

(SSR)
(CSR)
(MVC)
(Template-Engine) as (TEngine)
(Use-Case) as (UseCase)
(Aktoren)
(Funktionale Anforderungen) as (Anforderungen)
(Testszenario)
(Testfall)

(Anforderungen) "Braucht es für" --> (UseCase)

(Testszenario) "Testet" --> (UseCase)

(Testszenario) "Testet" --> (Anforderungen)

(Testszenario) "Haben" --> (Testfall)
(Testfall) "Erstellt" --> (Testszenario)

(UseCase) "Erstellt" --> (Testfall)

(UseCase) "Testet" --> (MVC)

(SSR) "Erfüllt gleiche Funktion" <--> (CSR)

(MVC) "Verwendet zum anzeigen" --> (SSR)
(MVC) "Verwendet zum anzeigen" --> (CSR)

(TEngine) "Generiert view von..." <--> "Verwendet" (MVC)

(UseCase) "Testet" --> (TEngine)

(Aktoren) "Verwenden view von..." --> (MVC)

(Aktoren) "Benutzer in..." --> (Testszenario)

@enduml
